version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  Core:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - run:
          name: Test
          command: yarn workspace apollo-angular test
      - run:
          name: Lint
          command: yarn workspace apollo-angular lint
  Boost:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build Core
          command: yarn workspace apollo-angular build
      - run:
          name: Build Common
          command: yarn workspace apollo-angular-link-http-common build
      - run:
          name: Build Http
          command: yarn workspace apollo-angular-link-http build
      - run:
          name: Test
          command: yarn workspace apollo-angular-boost test
      - run:
          name: Lint
          command: yarn workspace apollo-angular-boost lint

  Cache NgRx:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - run:
          name: Test
          command: yarn workspace apollo-angular-cache-ngrx test
      - run:
          name: Lint
          command: yarn workspace apollo-angular-cache-ngrx lint

  Link Headers:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - run:
          name: Test
          command: yarn workspace apollo-angular-link-headers test
      - run:
          name: Lint
          command: yarn workspace apollo-angular-link-headers lint

  Link Http:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build Common
          command: yarn workspace apollo-angular-link-http-common build
      - run:
          name: Test
          command: yarn workspace apollo-angular-link-http test
      - run:
          name: Lint
          command: yarn workspace apollo-angular-link-http lint

  Link Http Batch:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build Common
          command: yarn workspace apollo-angular-link-http-common build
      - run:
          name: Test
          command: yarn workspace apollo-angular-link-http-batch test
      - run:
          name: Lint
          command: yarn workspace apollo-angular-link-http-batch lint

  Link Http Common:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - run:
          name: Test
          command: yarn workspace apollo-angular-link-http-common test
      - run:
          name: Lint
          command: yarn workspace apollo-angular-link-http-common lint

  Link Persisted:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install
          command: yarn install
      - run:
          name: Test
          command: yarn workspace apollo-angular-link-persisted test
      - run:
          name: Lint
          command: yarn workspace apollo-angular-link-persisted lint

workflows:
  version: 2
  Build & Test:
    jobs:
      - install
      - Core:
          requires:
            - install
      - Boost:
          requires:
            - install
            - Core
            - Link Http
      - Cache NgRx:
          requires:
            - install
      - Link Headers:
          requires:
            - install
      - Link Http Common:
          requires:
            - install
      - Link Http:
          requires:
            - Link Http Common
      - Link Http Batch:
          requires:
            - Link Http Common
      - Link Persisted:
          requires:
            - install
